routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});




Route::get('/estacao', function () {
    return view('estacao');
});


//AUTH
Route::get('/login', 'AuthenController@login')->name('login');


Route::post('/login', 'AuthenController@checkUser');
Route::post('/logout', 'AuthenController@logout');
Route::post('/updatePwd', 'UtilizadoresController@updatePwd');


//Dashboard

Route::get('/pdf/{id}', 'PdfController@geraPdf')->name('gerar-pdf');
Route::get('/pdf2/{id}', 'PdfController@geraPdf2')->name('gerar-pdf2');

Route::get('/dashboard', 'TrafegoController@index')->name('dashboard');

//Ocorrencia
Route::resource('/ocorrencia', 'OcorrenciaController');


//PDF
Route::get('/dar-baixa', 'TrafegoController@darBaixa');

//Utilizador
Route::resource('/utilizador', 'UtilizadoresController');
Route::resource('/grafico', 'GraficoController');
Route::resource('/estacao', 'EstacoesController');
Route::resource('/registo', 'RegistosController');
Route::resource('/escoamento', 'EscoamentoController');

Route::get('/estacao/{estacao}', 'EstacoesController@toggleState')->name('toggle.state');

Route::get('/municipios/{provincia_id}', 'EstacoesController@MunicipiosByProvincia')->name('municipioRequest.get');
Route::get('/comuna/{municipio_id}', 'EstacoesController@ComunaByMunicipio')->name('comunaRequest.get');
Route::get('/grau-precedencia/{grau}', 'EscoamentoController@grauById');
Route::get('/grau-seguranca/{grauSe}', 'EscoamentoController@grauSegurancaById');


Route::get('/recebido/{id}', 'RegistosController@Recebidos');
Route::get('/invalido/{id}', 'RegistosController@Invalidos');

Route::get('/estatistica/occorencia', 'TrafegoController@ocorrencia')->name('statistics.occurs');
Route::get('/estatistica/trafego', 'TrafegoController@trafego')->name('statistics.traffic');
Route::get('/estatistica/estacao', 'TrafegoController@estacao')->name('statistics.estacao');
Route::post('/estatistica/imprimir', 'TrafegoController@print')->name('statistics.print');
//Route::get('/serie/{estacao_id}', 'EscoamentoController@getSerialNumber');

resources/views/escoamento_edit.blade.php
@extends('main')

@section('css')
    
  <link rel="stylesheet" href="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

@endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      SGT
      <small>Sistema de Gestão de Tráfego</small>
    </h1>
    <ol class="breadcrumb">
    
    <li><a href="/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Ocorrência</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Main row -->
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Ocorrência</h3>
            
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form action="{{ route('escoamento.update', $escoamento->id) }}" method="POST" role="form">
          @method('PUT')
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @elseif(session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
            <div class="box-body">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

           


           
               <div class="col-md-4">
                <div class="form-group">
                  <label>Tipo Trafego</label>
                  <select name="tipo_trafego_id" id="" class="form-control" required> 
                  <option value="">Seleciona Trafego </option>
                  @foreach( $tipoTrafego as $tf)
                      <option @if($tf->id == $escoamento->id_tipo_trafego) selected @endif value="{{ $tf->id }}">{{ $tf->descricao}} </option>
                    @endforeach
                  </select>
                </div>
               </div>

               <div class="col-md-4">
                <div class="form-group">
                  <label>Grau seguranca</label>
                  <select name="grau_seguranca_id" id="" class="form-control" required>
                  <option value="">Seleciona Grau de Seguranca </option>
                  @foreach( $grauSeguranca as $gs)
                      <option @if($gs->id == $escoamento->id_grau_seguranca) selected @endif value="{{ $gs->id }}">{{ $gs->descricao}} </option>
                    @endforeach
                  </select>  

                </div>
               </div>
               <div class="col-md-4">
                <div class="form-group">
                  <label>Grau Precedencia</label>
                  <select name="grau_precedencia_id" id="" class="form-control" required>
                  <option value="">Seleciona Grau de Precedencia </option>
                  @foreach( $grauPrecedencia as $gp)
                      <option @if($gp->id == $escoamento->id_grau_precedencia) selected @endif value="{{ $gp->id }}">{{ $gp->descricao}} </option>
                    @endforeach
                  </select>  

                </div>
               </div>
               <div class="col-md-4">
                <div class="form-group">
                  <label>Estação de Origem</label>
                  <input type="text" readonly value="{{ Auth::user()->estacao->codigo }} - {{ Auth::user()->estacao->nome }}" class="form-control">             
                </div>
               </div>


               <div class="col-md-4">
                <div class="form-group">
                  <label>Estação de Destino</label>
                  <select name="id_estacao_trabalho_recebe"  id="" class="form-control chosen-select" required>
                  <option value="">Seleciona Estação de Origem</option>
                    @foreach( $estacoes as $estacao)
                      @if($estacao->id != Auth::user()->estacao->id)
                        <option @if($estacao->id == $escoamento->id_estacao_trabalho_recebe) selected @endif value="{{ $estacao->id }}">{{ $estacao->nome}} </option>
                      @endif
                    @endforeach
                  </select>                  
                </div>
               </div>

               <div class="col-md-4">
                <div class="form-group">
                  <label>De.:</label>
                  <input type="text" name="envia" class="form-control" placeholder="Emissor" required value="{{ $escoamento->envia }}">
                </div>
               </div>
               <div class="col-md-4">
                <div class="form-group">
                  <label>Para.:</label>
                  <input type="text" name="recebe" class="form-control" placeholder="Receptor" required value="{{ $escoamento->recebe }}">
                </div>
               </div>
               <div class="col-md-2">
                <div class="form-group">
                  <label>Origem.:</label>
                  <input type="text" name="origem" class="form-control" required value="{{ $escoamento->origem }}">                                    
                </div>
               </div>
 

               <div class="col-md-2">
                <div class="form-group">
                  <label>Série.:</label>
                  <input type="number"  name="numero_serie"  class="form-control" required value="{{ $escoamento->numero_serie }}">
                 
                </div>
               </div>

               <div class="col-md-12">
                <div class="form-group">
           
           <textarea class="textarea1" name="mensagem" 
           style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" required  >{{ $escoamento->mensagem }}</textarea>
         
       </div>
          </div>

               </div>

                </div>
               </div>

            
            </div>
            <!-- /.box-body -->

            <div class="box-footer text-right">
              <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- /.row (main row) -->

  </section>
  <!-- /.content -->
</div>
@endsection

@section('js')
    
<!-- Bootstrap WYSIHTML5 -->
<script src="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script>
  $(function () {
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
</script>


@endsection

resources/views/form.blade.php
 <form action ="upload" method="post" enctype="multipart/form-data">
 
 @csrf()
 <input type="file" name="img">
 <br>
 <br>

 <button type="submit"> upload file 

</form>

resources/views/grafico.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        
<div id="graph">
 

{{!! $lava->render('BarChart', 'Pontuacao', 'graph')  !!}}


</div>

</body>
</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html>

<!-- Mirrored from adminlte.io/themes/AdminLTE/pages/examples/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 05 Nov 2019 14:15:34 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SGT - Login</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ URL::asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ URL::asset('bower_components/font-awesome/css/font-awesome.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ URL::asset('bower_components/Ionicons/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ URL::asset('dist/css/AdminLTE.min.css') }}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ URL::asset('plugins/iCheck/square/blue.css') }}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="fonts.googleapis.com/css5518.css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
   
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg"> <img src="dist/img/info.jpg"></p>
    
   

    <form action="login" method="post">
      @if (session('error'))
          <div class="alert alert-danger">
              {{ session('error') }}
          </div>
      @endif

      
      
      <div class="form-group has-feedback">
        <input type="text" name="codigo" class="form-control" placeholder="Codigo de Utilizador" autocomplete="off" required>
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <span class="fa fa-user form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <input type="password" name="password" class="form-control" placeholder="Senha" required>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>

      <div class="row">
        <!-- /.col -->
        <div class="col-xs-12">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Entrar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <div class="social-auth-links text-center">
     

    </div>
    <!-- /.social-auth-links -->

  
    

  </div>
  <!-- /.login-box-body -->
</div>

   <style type="text/css">
           
            img{

             height: 60%; 
             width: 60%;

              }

             body{
 
                background-image:url("2.jpg"); 
             }
                </style>

<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{{ URL::asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ URL::asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
</body>

<!-- Mirrored from adminlte.io/themes/AdminLTE/pages/examples/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 05 Nov 2019 14:15:34 GMT -->
</html>

resources/views/ocorrencia.blade.php
@extends('main')

@section('css')
    
  <link rel="stylesheet" href="{{ URL::asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

 
  @endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      SGT
      <small>Sistema de Gestão de Tráfego</small>
    </h1>
    <ol class="breadcrumb">
    <li><a href="/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Ocorrência</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Main row -->
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Ocorrência</h3>
            
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form action="{{ route('ocorrencia.store') }}" method="POST" role="form">
          @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @elseif(session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
            <div class="box-body">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <div class="col-md-4">
                <div class="form-group">
                  <label>Tipo Ocorrencia</label>
                  <select name="tipo_ocorrencia_id" id="" class="form-control" required>
                  <option value="">Seleciona o Tipo de Ocorrencia</option>
                    @foreach( $ocorrencia as $oc)
                      <option value="{{ $oc->id }}">{{ $oc->descricao}} </option>
                    @endforeach
                  </select>  

                </div>
               </div>
               <br>
           
            
               <div class="col-md-12">
                <div class="form-group">
           
           <textarea class="" name="mensagem" 
           style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
         
       </div>
       <div class="box-footer text-right">
              <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
          </div>
            <!-- /.box-body -->

           
          </form>
        </div>
      </div>

      
    </div>
    <!-- /.row (main row) -->

  </section>
  <!-- /.content -->
</div>
@endsection

@section('js')
    
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ URL::asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
 

 


@endsection

resources/views/registo_edit.blade.php
@extends('main')

@section('css')
    
  <link rel="stylesheet" href="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

@endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      SGT
      <small>Sistema de Gestão de Tráfego</small>
    </h1>
    <ol class="breadcrumb">
    <li><a href="/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Ocorrência</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Main row -->
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Ocorrência</h3>
            
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form action="{{ route('registo.update', $registo->id) }}" method="POST" role="form">
          @method('PUT')
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @elseif(session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
            <div class="box-body">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

           


            <div class="col-md-4">
                <div class="form-group">
                  <label>Tipo Operação</label>
                  <select name="tipo_operacao_id" id="" class="form-control" required> 
                    <option value="">Seleciona Operação </option>
                    @foreach( $tipoOperacao as $op)
                      <option @if($op->id == $registo->id_tipo_operacao) selected @endif value="{{ $op->id }}">{{ $op->descricao}} </option>
                    @endforeach
 
                  </select>
                </div>
               </div>
               <div class="col-md-4">
                <div class="form-group">
                  <label>Tipo Trafego</label>
                  <select name="tipo_trafego_id" id="" class="form-control" required> 
                  <option value="">Seleciona Trafego </option>
                  @foreach( $tipoTrafego as $tf)
                      <option @if($tf->id == $registo->id_tipo_trafego) selected @endif value="{{ $tf->id }}">{{ $tf->descricao}} </option>
                    @endforeach
                  </select>
                </div>
               </div>

               <div class="col-md-4">
                <div class="form-group">
                  <label>Grau seguranca</label>
                  <select name="grau_seguranca_id" id="" class="form-control" required>
                  <option value="">Seleciona Grau de Seguranca </option>
                  @foreach( $grauSeguranca as $gs)
                      <option @if($gs->id == $registo->id_grau_seguranca) selected @endif value="{{ $gs->id }}">{{ $gs->descricao}} </option>
                    @endforeach
                  </select>  

                </div>
               </div>
               <div class="col-md-4">
                <div class="form-group">
                  <label>Grau Precedencia</label>
                  <select name="grau_precedencia_id" id="" class="form-control" required>
                  <option value="">Seleciona Grau de Precedencia </option>
                  @foreach( $grauPrecedencia as $gp)
                      <option @if($gp->id == $registo->id_grau_precedencia) selected @endif value="{{ $gp->id }}">{{ $gp->descricao}} </option>
                    @endforeach
                  </select>  

                </div>
               </div>


               <div class="col-md-4">
                <div class="form-group">
                  <label>Estação de Origem</label>
                  <input type="text" readonly value="{{ Auth::user()->estacao->codigo }} - {{ Auth::user()->estacao->nome }}" class="form-control">             
                </div>
               </div>


               <div class="col-md-4">
                <div class="form-group">
                  <label>Estação de Destino</label>
                  <select name="id_estacao_trabalho_recebe"  id="" class="form-control chosen-select" required>
                  <option value="">Seleciona Estação de Origem</option>
                    @foreach( $estacoes as $estacao)
                      @if($estacao->id != Auth::user()->estacao->id)
                        <option @if($estacao->id == $registo->id_estacao_trabalho_recebe) selected @endif value="{{ $estacao->id }}">{{ $estacao->nome}} </option>
                      @endif
                    @endforeach
                  </select>                  
                </div>
               </div>

               <div class="col-md-4">
                <div class="form-group">
                  <label>De.:</label>
                  <input type="text" name="envia" class="form-control" placeholder="Emissor" required value="{{ $registo->envia }}">
                </div>
               </div>
               <div class="col-md-4">
                <div class="form-group">
                  <label>Para.:</label>
                  <input type="text" name="recebe" class="form-control" placeholder="Receptor" required value="{{ $registo->recebe }}">
                </div>
               </div>
               <div class="col-md-2">
                <div class="form-group">
                  <label>Origem.:</label>
                  <input type="text" name="origem" class="form-control" required value="{{ $registo->origem }}">                                    
                </div>
               </div>

               

               <div class="col-md-2">
                <div class="form-group">
                  <label>Ano.:</label>
                  <input type="number" class="form-control" name="ano" onkeypress="return event.charCode >= 48 && event.charCode <= 57"  maxlength="4" required value="{{ $registo->ano }}">

                </div>
               </div>

               <div class="col-md-2">
                <div class="form-group">
                  <label>Série.:</label>
                  <input type="text"  name="serie"  class="form-control" onkeydown="javascript: fMasc( this, mCPF );"maxlength="8"  value="{{ $registo->serie }}">
                   
                </div>
               </div>
               </div>

                </div>
               </div>

            
            </div>
            <!-- /.box-body -->

            <div class="box-footer text-right">
              <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- /.row (main row) -->

  </section>
  <!-- /.content -->
</div>
@endsection

@section('js')
    
<!-- Bootstrap WYSIHTML5 -->
<script src="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script>
  $(function () {
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
</script>


@endsection

resources/views/ver_ocorrencia.blade.php
@extends('main')

@section('css')

<!-- DataTables -->
<link rel="stylesheet" href="bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

@endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            SGT
            <small>Sistema de Gestão de Tráfego</small>
        </h1>
        <ol class="breadcrumb">
        <li><a href="/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Lista Ocorrencia</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @elseif(session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
             
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Lista de Ocorrencias</h3>
                        
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-lg-12">
                                    <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                                        <thead>
                                            <tr>
                                               
                                                <th>#</th>
                                                <th>Tipo de Ocorrencia</th>
                                                <th>Usuário</th>
                                                <th>Data</th>
                                              <th class="text-center">Ação</th>  
                                            </tr>
                                        </thead>
 

 
                                        <tbody>
                                            {{ $a = 1 }}
                                            @foreach($ocorrencias as $ocorrencia)
                                                      
                                            
                                                @if($ocorrencia->id_usuario == Auth::user()->id)
                                                       
                                                    <tr>    
                                                        <td>{{ $a }}</td>
                                                        <td>{{ $ocorrencia->tipo_ocorrencia->descricao }}</td>
                                                        <td>{{ $ocorrencia->usuario->nome }}</td> 
                                                        <td>{{ $ocorrencia->created_at }}</td> 
                                                        <td class="text-center">
                                                            
                                                        <form action="{{ route('ocorrencia.destroy', $ocorrencia->id) }}" method="POST">
                                                                @method('DELETE')
                                                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                                        
                                                                        <a href="{{ $ocorrencia->id }}" class="btn btn-sm btn-success" data-toggle="modal" data-target="#exampleModal-{{  $ocorrencia->id }}">  <i class="fa fa-eye"></i>  </a>
                                                                <a href="{{ route('ocorrencia.edit', $ocorrencia->id) }}" class="btn btn-sm btn-primary"> Editar </a>

                                                                <button class="btn btn-sm btn-danger">Excluir</button>
                                                            </form>
                                                        </td>
                                                    </tr>                                                 
                                                @endif  
                                            {{ $a++ }}

                                                                                    
                                    
                                <div class="modal fade" id="exampleModal-{{  $ocorrencia->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Ocorrencia</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        
                                    {{ $ocorrencia->mensagem }}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Sair</button>
                                    
                                    </div>
                                    </div>
                                </div>
                                </div>
       
                                            @endforeach
                                        </tbody>
                                    
                                    </table>
</div><br> <br> <br> <br> <br>
                                </div>
                                <!-- /.box-body -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row (main row) -->

    </section>
    
                      <!-- Modal -->


                       
       
@endsection
@section('js')

<!-- DataTables -->
<script src="bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

<!-- page script -->
<script>
    $(function() {
        $('#example1').DataTable()
    })
</script>

@endsection