routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});




Route::get('/estacao', function () {
    return view('estacao');
});


//AUTH
Route::get('/login', 'AuthenController@login')->name('login');


Route::post('/login', 'AuthenController@checkUser');
Route::post('/logout', 'AuthenController@logout');
Route::post('/updatePwd', 'UtilizadoresController@updatePwd');


//Dashboard

Route::get('/pdf/{id}', 'PdfController@geraPdf')->name('gerar-pdf');
Route::get('/pdf2/{id}', 'PdfController@geraPdf2')->name('gerar-pdf2');

Route::get('/dashboard', 'TrafegoController@index')->name('dashboard');

//Ocorrencia
Route::resource('/ocorrencia', 'OcorrenciaController');


//PDF
Route::get('/dar-baixa', 'TrafegoController@darBaixa');

//Utilizador
Route::resource('/utilizador', 'UtilizadoresController');
Route::resource('/grafico', 'GraficoController');
Route::resource('/estacao', 'EstacoesController');
Route::resource('/registo', 'RegistosController');
Route::resource('/escoamento', 'EscoamentoController');

Route::get('/estacao/{estacao}', 'EstacoesController@toggleState')->name('toggle.state');

Route::get('/municipios/{provincia_id}', 'EstacoesController@MunicipiosByProvincia')->name('municipioRequest.get');
Route::get('/comuna/{municipio_id}', 'EstacoesController@ComunaByMunicipio')->name('comunaRequest.get');
Route::get('/grau-precedencia/{grau}', 'EscoamentoController@grauById');
Route::get('/grau-seguranca/{grauSe}', 'EscoamentoController@grauSegurancaById');


Route::get('/recebido/{id}', 'RegistosController@Recebidos');
Route::get('/invalido/{id}', 'RegistosController@Invalidos');

Route::get('/estatistica/occorencia', 'TrafegoController@ocorrencia')->name('statistics.occurs');
Route::get('/estatistica/trafego', 'TrafegoController@trafego')->name('statistics.traffic');
Route::get('/estatistica/estacao', 'TrafegoController@estacao')->name('statistics.estacao');
Route::post('/estatistica/imprimir', 'TrafegoController@print')->name('statistics.print');
//Route::get('/serie/{estacao_id}', 'EscoamentoController@getSerialNumber');

app/Http/Controllers/EstacoesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\estacao_trabalho;
use App\Models\municipio;
use App\Models\comuna;
use App\usuarios;
use App\Models\provincia;
use Illuminate\Support\Facades\Auth;



class EstacoesController extends Controller
{

    protected $months = [
        "01" => "Janeiro",
        "02" => "Fevereiro",
        "03" => "Março",
        "04" => "Abril",
        "05" => "Maio",
        "06" => "Junho",
        "07" => "Julho",
        "08" => "Agosto",
        "09" => "Setembro",
        "10" => "Outubro",
        "11" => "Novembro",
        "12" => "Dezembro"
    ];

    protected $years = [
        "2020" => "2020",
        "2019" => "2019",
        "2018" => "2018"
    ];


    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('estacoes.index')->withEstacoes(estacao_trabalho::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->nivel == 'Admin') {
            return view('estacoes.create')->withProvincias(provincia::all())->withMunicipios(municipio::where("provincia_id", Auth::user()->estacao->municipio->provincia_id)->get());
        }
        return view('estacoes.create')->withProvincias(provincia::all())->withMunicipios(municipio::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $estacao = new estacao_trabalho();

        $estacao->nome = $request->nome;
        $estacao->tipo = $request->tipo;
        $estacao->municipio_id = $request->municipio_id;

        $__Verifica = estacao_trabalho::where('municipio_id', $request->municipio_id)
            ->where('nome', $request->nome)
            ->where('tipo', $request->tipo)
            ->count();

        if ($__Verifica < 1) {


            if ($estacao->save()) {

                $comuna = new comuna();

                $comuna->nome = $request->nome;

                $comuna->estacao_id = $estacao->id;

                $comuna->save();

                return redirect('estacao')->with('success', 'Estação cadastrada!');
            } else {

                return redirect('estacao')->with('error', 'Não foi possível cadastrar a estação!');
            }
        } else {

            return redirect('estacao')->with('error', 'Já existe uma estação com os dados inseridos');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function toggleState(estacao_trabalho $estacao)
    {
        $estacao->estado = ($estacao->estado == "Activa") ? "Inactiva" : "Activa";
        if ($estacao->save()) {

            return redirect('estacao')->with('success', 'Dados atualizados!');
        } else {

            return redirect('estacao')->with('error', 'Não foi possível atualizar os dados da estação!');
        }
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Estacao = estacao_trabalho::find($id);
        return view('estacoes.edit')->withEstacao(estacao_trabalho::find($id))->withProvincias(provincia::all())->withMunicipios(municipio::where("provincia_id", $Estacao->municipio->provincia_id)->get());
    }

    public function MunicipiosByProvincia($provincia_id)
    {

        return response()->json(municipio::where("provincia_id", $provincia_id)->get());
    }

    public function ComunaByMunicipio($municipio_id)
    {

        return response()->json(estacao_trabalho::where("municipio_id", $municipio_id)->where("tipo", "Comunal")->get());
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, estacao_trabalho $estacao)
    {

        $estacao->nome = $request->nome;
        $estacao->tipo = $request->tipo;
        $estacao->municipio_id = $request->municipio_id;

        if ($estacao->save()) {

            return redirect('estacao')->with('success', 'Dados atualizados!');
        } else {

            return redirect('estacao')->with('error', 'Não foi possível atualizar os dados da estação!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $estacao = estacao_trabalho::find($id);

        $__envolved_on_user = usuarios::where('id_estacao_trabalho', $id)->count();
        //$__envolved_on_form = usuarios::where('id_usuario', $id)->count();

        if ($__envolved_on_user) {

            return redirect('estacao')->with('error', 'Não é possível eliminar a estação <strong>"' . $estacao->nome . '"</strong>, pois já existem usuários vinculados a mesma.');
        }

        $estacao->delete();
        return redirect('estacao')->with('success', 'Estação eliminada');
    }
}

resources/views/estacoes/create.blade.php
@extends('main')

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      SGT
      <small>Sistema de Gestão de Tráfego</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Estações</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Main row -->
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Nova Estação</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" action="{{ route('estacao.store') }} " method="POST">
            <div class="box-body">

              <div class="col-md-3">
                <div class="form-group">
                  <label>Nome</label>
                  <input type="text" name="nome" class="form-control" autocomplete="off" required>
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </div>
              </div>

              @if(Auth::user()->nivel=='Admin')

              <div class="col-md-3">
                <div class="form-group">
                  <label>Tipo</label>
                  <select name="tipo" class="form-control" required>
                    <option selected disabled value="">Selecione tipo de Estação</option>
                    <option value="Municipal">Municipal</option>
                    <option value="Comunal">Comunal</option>
                  </select>
                </div>
              </div>

              @else()

              <div class="col-md-3">
                <div class="form-group">
                  <label>Tipo</label>
                  <select name="tipo" class="form-control" required>
                    <option selected disabled value="">Selecione tipo de Estação</option>
                    <option value="Sede">Sede</option>
                    <option value="Municipal">Municipal</option>
                    <option value="Comunal">Comunal</option>
                  </select>
                </div>
              </div>

              @endif


              @if(Auth::user()->nivel=='Admin' )

              <div class="col-md-3">
                <div class="form-group">
                  <label>Província</label>
                  <input type="text" readonly value="{{ Auth::user()->estacao->municipio->provincia->nome }} - {{ Auth::user()->estacao->municipio->provincia->codigo }}" class="form-control">
                </div>
              </div>

              @else

              <div class="col-md-3">
                <div class="form-group">
                  <label>Província</label>
                  <select name="provincia_id" class="form-control select-provincia" required>
                    <option selected disabled value="">Selecione uma província</option>
                    @foreach($provincias as $provincia)
                    <option value="{{ $provincia->id }}">{{ $provincia->nome }} - {{ $provincia->codigo }}</option>
                    @endforeach
                  </select>
                </div>
              </div>

              @endif

              <div class="col-md-3">
                <div class="form-group">
                  <label>Município</label>
                  <select name="municipio_id" class="form-control" required>
                    @foreach($municipios as $municipio)
                      <option value="{{ $municipio->id }}">{{ $municipio->nome }}</option>
                    @endforeach
                  </select>
                </div>
              </div> 

            </div>
            <!-- /.box-body -->

            <div class="box-footer text-right">
              <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- /.row (main row) -->

  </section>
  <!-- /.content -->
</div>
@endsection
@section('js')
<script type="text/javascript">

$(document).on('change', '.select-provincia', function() {
  $("[name=municipio_id]").html('<option selected disabled value="">Selecione um município</option>');
  let prov_id = $(this).val();
  $.ajax({
        'async': false,
        'type': "GET",
        'global': false,
        'dataType': 'json',
        'url': "/public/municipios/"+prov_id,
        'data': {
            'request': "",
            'target': 'arrange_url',
            'method': 'method_target'
        },
        'success': function(data) {
            //console.log(data);
            for (var i = 0; i < data.length; i++) {
                $("[name=municipio_id]").append('<option value="' + data[i].id + '">' + data[i].nome + '</option>');
            }
        }
    });
});

</script>
@endsection

resources/views/estacoes/edit.blade.php
@extends('main')

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      SGT
      <small>Sistema de Gestão de Tráfego</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Estações</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Main row -->
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Editar Estação</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" action="{{ route('estacao.update', $estacao->id) }}" method="POST">
            @method('PUT')
            <div class="box-body">

              <div class="col-md-3">
                <div class="form-group">
                  <label>Nome</label>
                  <input type="text" name="nome" class="form-control" value="{{ $estacao->nome }}" required>
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </div>
              </div>

              @if(Auth::user()->nivel=='Admin' )

              <div class="col-md-3">
                <div class="form-group">
                  <label>Tipo</label>
                  <select name="tipo" class="form-control" required>
                    <option selected disabled value="">Selecione tipo de Estação</option>
                    <option @if($estacao->tipo == 'Municipal') selected @endif value="Municipal">Municipal</option>
                    <option @if($estacao->tipo == 'Comunal') selected @endif value="Comunal">Comunal</option>
                  </select>
                </div>
              </div>

              @else()

              <div class="col-md-3">
                <div class="form-group">
                  <label>Tipo</label>
                  <select name="tipo" class="form-control" required>
                    <option selected disabled value="">Selecione tipo de Estação</option>
                    <option @if($estacao->tipo == 'Sede') selected @endif value="Sede">Sede</option>
                    <option @if($estacao->tipo == 'Municipal') selected @endif value="Municipal">Municipal</option>
                    <option @if($estacao->tipo == 'Comunal') selected @endif value="Comunal">Comunal</option>
                  </select>
                </div>
              </div>

              @endif


              @if(Auth::user()->nivel=='Admin' )

              <div class="col-md-3">
                <div class="form-group">
                  <label>Província</label>
                  <input type="text" readonly value="{{ Auth::user()->estacao->municipio->provincia->nome }} - {{ Auth::user()->estacao->municipio->provincia->codigo }}" class="form-control">
                </div>
              </div>

              @else

              <div class="col-md-3">
                <div class="form-group">
                  <label>Província</label>
                  <select name="provincia_id" class="form-control select-provincia" required>
                    <option selected disabled value="">Selecione uma província</option>
                    @foreach($provincias as $provincia)
                    <option @if($estacao->municipio->provincia_id == $provincia->id) selected @endif value="{{ $provincia->id }}">{{ $provincia->nome }} - {{ $provincia->codigo }}</option>
                    @endforeach
                  </select>
                </div>
              </div>

              @endif
              
              <div class="col-md-3">
                <div class="form-group">
                  <label>Município</label>
                  <select name="municipio_id" class="form-control" required>
                    <option selected disabled value="">Selecione uma província</option>
                    @foreach($municipios as $municipio)
                    <option @if($estacao->municipio_id == $municipio->id) selected @endif value="{{ $municipio->id }}">{{ $municipio->nome }}</option>
                    @endforeach
                  </select>
                </div>
              </div>

            </div>
            <!-- /.box-body -->

            <div class="box-footer text-right">
              <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- /.row (main row) -->

  </section>
  <!-- /.content -->
</div>
@endsection
@section('js')
<script type="text/javascript">
  $(document).on('change', '.select-provincia', function() {
    $("[name=municipio_id]").html('<option selected disabled value="">Selecione um município</option>');
    let prov_id = $(this).val();
    $.ajax({
      'async': false,
      'type': "GET",
      'global': false,
      'dataType': 'json',
      'url': "/public/municipios/" + prov_id,
      'data': {
        'request': "",
        'target': 'arrange_url',
        'method': 'method_target'
      },
      'success': function(data) {
        //console.log(data);
        for (var i = 0; i < data.length; i++) {
          $("[name=municipio_id]").append('<option value="' + data[i].id + '">' + data[i].nome + '</option>');
        }
      }
    });
  });
</script>
@endsection

resources/views/estacoes/index.blade.php
@extends('main')

@section('css')

<!-- DataTables -->
<link rel="stylesheet" href="bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

@endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            SGT
            <small>Sistema de Gestão de Tráfego</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Estações</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @elseif(session('error'))
                    <div class="alert alert-danger">
                        {!! session('error') !!}
                    </div>
                @endif
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Estações</h3>
                        <div class="text-right" style="margin-top: -25px;">
                            <a href="{{ route('estacao.create') }}" class="btn btn-primary">
                                <i class="fa fa-plus-circle"></i>
                                Nova Estação
                            </a>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-lg-12">
                                    <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Nome</th>
                                                <th>Tipo</th>
                                                <th>Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $a = 1; ?>
                                           
                                            @foreach($estacoes as $estacao)
                                           
                                                <tr>
                                                    <td>{{ $a }}</td>
                                                    <td>{{ $estacao->nome }} - {{ $estacao->municipio->provincia->codigo }}</td>
                                                    <td>{{ $estacao->tipo }}</td>
                                                    <td class="text-center">
                                                        <form action="{{ route('estacao.destroy', $estacao->id) }}" method="POST">
                                                            @method('DELETE')
                                                            <a href="{{ route('estacao.edit', $estacao->id) }}" class="btn btn-sm btn-primary">Editar</a>
                                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                            <button class="btn btn-sm btn-danger">Excluir</button>
                                                            <a href="{{ route('toggle.state', $estacao->id) }}" class="btn btn-sm btn-warning">{{ ($estacao->estado == "Activa") ? "Desactivar" : "Activar"}}</a>
                                                        </form>
                                                    </td>
                                                </tr>
                                               
                                            
                                            <?php $a++; ?>
                                          

                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.box-body -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row (main row) -->

    </section>
    <!-- /.content -->
</div>
@endsection
@section('js')

<!-- DataTables -->
<script src="bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

<!-- page script -->
<script>
    $(function() {
        $('#example1').DataTable()
    })
</script>

@endsection