routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});




Route::get('/estacao', function () {
    return view('estacao');
});


//AUTH
Route::get('/login', 'AuthenController@login')->name('login');


Route::post('/login', 'AuthenController@checkUser');
Route::post('/logout', 'AuthenController@logout');
Route::post('/updatePwd', 'UtilizadoresController@updatePwd');


//Dashboard

Route::get('/pdf/{id}', 'PdfController@geraPdf')->name('gerar-pdf');
Route::get('/pdf2/{id}', 'PdfController@geraPdf2')->name('gerar-pdf2');

Route::get('/dashboard', 'TrafegoController@index')->name('dashboard');

//Ocorrencia
Route::resource('/ocorrencia', 'OcorrenciaController');


//PDF
Route::get('/dar-baixa', 'TrafegoController@darBaixa');

//Utilizador
Route::resource('/utilizador', 'UtilizadoresController');
Route::resource('/grafico', 'GraficoController');
Route::resource('/estacao', 'EstacoesController');
Route::resource('/registo', 'RegistosController');
Route::resource('/escoamento', 'EscoamentoController');

Route::get('/estacao/{estacao}', 'EstacoesController@toggleState')->name('toggle.state');

Route::get('/municipios/{provincia_id}', 'EstacoesController@MunicipiosByProvincia')->name('municipioRequest.get');
Route::get('/comuna/{municipio_id}', 'EstacoesController@ComunaByMunicipio')->name('comunaRequest.get');
Route::get('/grau-precedencia/{grau}', 'EscoamentoController@grauById');
Route::get('/grau-seguranca/{grauSe}', 'EscoamentoController@grauSegurancaById');


Route::get('/recebido/{id}', 'RegistosController@Recebidos');
Route::get('/invalido/{id}', 'RegistosController@Invalidos');

Route::get('/estatistica/occorencia', 'TrafegoController@ocorrencia')->name('statistics.occurs');
Route::get('/estatistica/trafego', 'TrafegoController@trafego')->name('statistics.traffic');
Route::get('/estatistica/estacao', 'TrafegoController@estacao')->name('statistics.estacao');
Route::post('/estatistica/imprimir', 'TrafegoController@print')->name('statistics.print');
//Route::get('/serie/{estacao_id}', 'EscoamentoController@getSerialNumber');

app/usuarios.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\estacao_trabalho; 

class usuarios extends Authenticatable
{
    protected $table = 'tbl_usuario';

    public function estacao()
    {
        return $this->belongsTo(estacao_trabalho::class, 'id_estacao_trabalho');
    }
    
}

resources/views/usuarios/create.blade.php
@extends('main')

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
     <h1>
       SGT
      <small>Sistema de Gestão de Tráfego</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Utilizadores</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Main row -->
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Novo Utilizador</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" action="{{ route('utilizador.store') }}" method="POST">
            <div class="box-body">

              <div class="col-md-4">
               <div class="form-group">
                 <label>Codigo</label>
                 <input type="hidden" name="_token" value="{{ csrf_token() }}">
                 <input type="text" name="codigo" disabled value="(auto)" class="form-control">
               </div>
              </div>

              <div class="col-md-4">
               <div class="form-group">
                 <label>Nome</label>
                 <input type="text" name="nome" class="form-control" required>
               </div>
              </div>

              <div class="col-md-4">
               <div class="form-group">
                 <label>Senha</label>
                 <input type="text" name="password" class="form-control" required>                  
               </div>
              </div>
              
               
 
              @if(Auth::user()->nivel=='Admin' )
          
              <div class="col-md-4">
                <div class="form-group">
                  <label>Nível de Acesso:</label>
                  <input type="text" name="nivel" readonly value="Usuário" class="form-control">
                </div>
               </div>
                  

            @else  
            
             <div class="col-md-4">
               <div class="form-group">
                 <label>Nível de Acesso</label>
                 <select name="nivel" class="form-control" required>
                   <option selected disabled value="">Selecione o nível de acesso</option>
                   <option value="Admin">Admin</option>
                   <option value="Usuário">Usuário</option>
                   <option value="SuperUsuário">Super Usuário</option>
                   <option value="Estatístico">Estatístico</option>
                 </select>                  
               </div>
              </div>
           
            @endif

              <div class="col-md-4">
               <div class="form-group">
                 <label>Estação de Trabalho</label>
                 <select name="id_estacao_trabalho" class="form-control chosen-select" required>
                  <option selected disabled value="">Selecione a estação</option>
                  @foreach($estacoes as $estacao)
                   @if(Auth::user()->nivel=='Admin')

                      @if(Auth::user()->estacao->municipio->provincia->id == $estacao->municipio->provincia->id)
                        <option value="{{ $estacao->id }}">{{ $estacao->municipio->provincia->codigo }} - {{ $estacao->nome }} ({{ $estacao->tipo }})</option>
                      @endif

                    @else
                    <option value="{{ $estacao->id }}">{{ $estacao->municipio->provincia->codigo }} - {{ $estacao->nome }} ({{ $estacao->tipo }})</option>
                    @endif
                  @endforeach
                 </select>                  
               </div>
              </div> 
              
            </div>
            <!-- /.box-body -->

            <div class="box-footer text-right">
              <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- /.row (main row) -->

  </section>
  <!-- /.content -->
</div>
@endsection

resources/views/usuarios/edit.blade.php
@extends('main')

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
     <h1>
       SGT
      <small>Sistema de Gestão de Tráfego</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Utilizadores</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Main row -->
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Novo Utilizador</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" action="{{ route('utilizador.update', $utilizador->id) }}" method="POST">
            @method('PUT')
            <div class="box-body">
              <div class="col-md-4">
               <div class="form-group">
                 <label>Codigo</label>
                 <input type="hidden" name="_token" value="{{ csrf_token() }}">
                 <input type="text" name="codigo" disabled value="{{ $utilizador->codigo }}" class="form-control">
               </div>
              </div>

              <div class="col-md-4">
               <div class="form-group">
                 <label>Nome</label>
                 <input type="text" name="nome" value="{{ $utilizador->nome }}" class="form-control" required>
               </div>
              </div>

              <div class="col-md-4">
               <div class="form-group">
                 <label>Nova Senha (Opcional)</label>
                 <input type="text" name="password" class="form-control">                  
               </div>
              </div>

              @if(Auth::user()->nivel=='Admin' )
          
            <div class="col-md-4">
              <div class="form-group">
                <label>Nível de Acesso:</label>
                <input type="text" name="nivel" readonly value="Usuário" class="form-control">
              </div>
            </div>
              

          @else  
        
         <div class="col-md-4">
           <div class="form-group">
             <label>Nível de Acesso</label>
             <select name="nivel" class="form-control" required>
               <option selected disabled value="">Selecione o nível de acesso</option>
               <option @if($utilizador->nivel == 'Admin') selected @endif value="Admin">Admin</option>
               <option @if($utilizador->nivel == 'Usuário') selected @endif value="Usuário">Usuário</option>
               <option @if($utilizador->nivel == 'SuperUsuário') selected @endif value="SuperUsuário">Super Usuário</option>
             </select>                  
           </div>
          </div>
       
        @endif

        <div class="col-md-4">
        <div class="form-group">
          <label>Estação de Trabalho</label>
          <select name="id_estacao_trabalho" class="form-control chosen-select" required>
            <option selected disabled value="">Selecione a estação</option>
            @foreach($estacoes as $estacao)
              @if(Auth::user()->nivel=='Admin')

                @if(Auth::user()->estacao->municipio->provincia->id == $estacao->municipio->provincia->id)
                  <option @if($utilizador->id_estacao_trabalho == $estacao->id) selected @endif value="{{ $estacao->id }}">{{ $estacao->municipio->provincia->codigo }} - {{ $estacao->nome }} ({{ $estacao->tipo }})</option>
                @endif

              @else
                <option @if($utilizador->id_estacao_trabalho == $estacao->id) selected @endif value="{{ $estacao->id }}">{{ $estacao->municipio->provincia->codigo }} - {{ $estacao->nome }} ({{ $estacao->tipo }})</option>
              @endif
            @endforeach
          </select>                  
        </div>
        </div>
        </div>

            </div>
            <!-- /.box-body -->

            <div class="box-footer text-right">
              <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- /.row (main row) -->

  </section>
  <!-- /.content -->
</div>
@endsection

resources/views/usuarios/index.blade.php
@extends('main')

@section('css')

<!-- DataTables -->
<link rel="stylesheet" href="bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

@endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            SGT
            <small>Sistema de Gestão de Tráfego</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Utilizadores</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @elseif(session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Utilizadores</h3>
                        <div class="text-right" style="margin-top: -25px;">
                            <a href="{{ route('utilizador.create') }}" class="btn btn-primary">
                                <i class="fa fa-plus-circle"></i>
                                Novo Utilizador
                            </a>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-lg-12">
                                    <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Codigo</th>
                                                <th>Nome</th>
                                                <th>Nivel</th>
                                                <th>Estação</th>
                                                <th>Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $a = 1; ?>
                                           
                                            @foreach($utilizadores as $utilizador)
                                                @if(Auth::user()->nivel == "Admin" && $utilizador->estacao->municipio->provincia->id == Auth::user()->estacao->municipio->provincia->id)
                                                <tr>
                                                    <td>{{ $a }}</td>
                                                    <td>{{ $utilizador->codigo }}</td>
                                                    <td>{{ $utilizador->nome }}</td>
                                                    <td>{{ $utilizador->nivel }}</td>
                                                    <td>{{ $utilizador->estacao->municipio->provincia->codigo }} - {{ $utilizador->estacao->nome }} ({{ $utilizador->estacao->tipo }})</td>
                                                    <td class="text-center">
                                                        <form action="{{ route('utilizador.destroy', $utilizador->id) }}" method="POST">
                                                            @method('DELETE')
                                                            <a href="{{ route('utilizador.edit', $utilizador->id) }}" class="btn btn-sm btn-primary">Editar</a>
                                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">

                                                           
                                                            <button class="btn btn-sm btn-danger">Excluir</button>

                                                           
                                                        </form>
                                                    </td>
                                                </tr>
                                                @else
                                                <tr>
                                                    <td>{{ $a }}</td>
                                                    <td>{{ $utilizador->codigo }}</td>
                                                    <td>{{ $utilizador->nome }}</td>
                                                    <td>{{ $utilizador->nivel }}</td>
                                                    <td>{{ $utilizador->estacao->municipio->provincia->codigo }} - {{ $utilizador->estacao->nome }} ({{ $utilizador->estacao->tipo }})</td>
                                                    <td class="text-center">
                                                        <form action="{{ route('utilizador.destroy', $utilizador->id) }}" method="POST">
                                                            @method('DELETE')
                                                            <a href="{{ route('utilizador.edit', $utilizador->id) }}" class="btn btn-sm btn-primary">Editar</a>
                                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">

                                                           
                                                            <button class="btn btn-sm btn-danger">Excluir</button>

                                                           
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endif
                                            <?php $a++; ?>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.box-body -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row (main row) -->

    </section>
    <!-- /.content -->
</div>
@endsection
@section('js')

<!-- DataTables -->
<script src="bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

<!-- page script -->
<script>
    $(function() {
        $('#example1').DataTable()
    })
</script>

@endsection